apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - image: asia.gcr.io/linguist-2a182/frontend:41
        name: frontend
        ports:
        - containerPort: 3000
          name: http-server
