apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    run: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
      - name: backend
        image: asia.gcr.io/linguist-2a182/backend:89
        ports:
        - containerPort: 3000
        - containerPort: 443 
