apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: asia.gcr.io/linguist-2a182/backend:41
        name: web
        ports:
        - containerPort: 3000
          name: http-server
