apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  loadBalancerIP: "35.190.57.67"
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: web
