apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: asia.gcr.io/linguist-2a182/backend:41
        name: web
        ports:
        - containerPort: 3000
          name: http-server

